### ISSUE TITLE
Can't Change Spawn Frequency

### ISSUE THREAD

**Issue by AntumDeluge** [Rui-Minetest/creeper#6]
There is a massive amount of creepers on my server. I tried changing the values of "interval" & "chance" in the spawn.lua script, but it doesn't seem to make any difference. The world is still overloaded with creepers. How can I make them spawn less frequently?

**Comment by Rui914** [comment]
```
local objs = minetest.get_objects_inside_radius(pos, 12)
for _, obj in pairs(objs) do
	local luaentity = obj:get_luaentity()
	if luaentity and luaentity.name == "creeper:creeper" then
		return
	end
end
```
Can you write this code into action of ABM?


Note: This mod is too old. To be rewritten.

**Comment by AntumDeluge** [comment]
I'm sorry Rui, I think I was mistaken. It appeared that reducing the spawn rate wasn't working because all the creepers that had previously spawned were saved in the database. After removing the mod & using [PilzAdam's 'clean' mod](https://forum.minetest.net/viewtopic.php?t=2777) on 'creeper:creeper' for a while, I reintroduced the creeper with a much lower spawn rate (interval = 30, chance = 9000). Now I only run into one every once in a while.

Sorry for the confusion & thank you for the great mod.
